### ISSUE TITLE
What is the Code Licence? And what is the status of the App

### ISSUE THREAD

**Issue by Muhammad-Altabba** [fatihcandev/react-native-crypto-wallet-app#1]
Hello, 
What is the Code Licence is it MIT?
And what is the status of the app? Will there be further development?
I would like also to say that it will be nice to have a readme file ;)
Thanks,

**Comment by fatihcandev** [comment]
> Hello,
> What is the Code Licence is it MIT?
> And what is the status of the app? Will there be further development?
> I would like also to say that it will be nice to have a readme file ;)
> Thanks,

Hi. It was just a practice project. There will be no further development. You can use the code freely. I'll add a MIT licence file.
